<a href="https://colab.research.google.com/github/BraveSword123/Machine-Learning-Project/blob/main/Machine_Learning_Project_(Modeling%2C_Evaluation%2C_and_Deployment).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 4 - Data Cleaning

In [7]:
import pandas as pd
file_path = '/content/sample_data/housing.csv.csv'

housing_df = pd.read_csv(file_path)

# check
housing_df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [8]:
# set class/target attributte/col
target = 'median_house_value'

# check shape (i.e. # rows and # cols)
housing_df.shape

(20640, 10)

In [9]:
# identify cols with missing data
housing_df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [10]:
# check for duplicate rows
print('duplicated rows:', housing_df.duplicated().sum())

duplicated rows: 0

In [11]:
# remove/drop rows with missing data
missing_dropped_df = housing_df.dropna()

rows_dropped = housing_df.shape[0] - missing_dropped_df.shape[0]
print('rows dropped:', rows_dropped)

print('before dropping missing data rows:', housing_df.shape)
print('after dropping missing data rows:', missing_dropped_df.shape)

# removed data percentage
percent_lost = round((100*rows_dropped)/float(housing_df.shape[0]))
print(f'{percent_lost}% of rows removed from orignal dataset')

rows dropped: 207
before dropping missing data rows: (20640, 10)
after dropping missing data rows: (20433, 10)
1% of rows removed from orignal dataset

In [12]:
# compare dataset before and after removing missing values

# before
housing_df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [13]:
# after
missing_dropped_df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20433.000000,20433.000000,20433.000000,20433.000000,20433.000000,20433.000000,20433.000000,20433.000000,20433.000000
mean,-119.570689,35.633221,28.633094,2636.504233,537.870553,1424.946949,499.433465,3.871162,206864.413155
std,2.003578,2.136348,12.591805,2185.269567,421.385070,1133.208490,382.299226,1.899291,115435.667099
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1450.000000,296.000000,787.000000,280.000000,2.563700,119500.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.536500,179700.000000
75%,-118.010000,37.720000,37.000000,3143.000000,647.000000,1722.000000,604.000000,4.744000,264700.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [14]:
# change in mean before and after dropping missig data rows
((missing_dropped_df.mean(numeric_only=True) - housing_df.mean(numeric_only=True)) / housing_df.mean(numeric_only=True) * 100).round(2)

longitude             0.00
latitude              0.00
housing_median_age   -0.02
total_rooms           0.03
total_bedrooms        0.00
population           -0.04
households           -0.02
median_income         0.01
median_house_value    0.00
dtype: float64

In [15]:
# find outliers using IQR
Q1 = missing_dropped_df.quantile(0.25, numeric_only=True)
Q3 = missing_dropped_df.quantile(0.75, numeric_only=True)
IQR = Q3 - Q1
print(IQR)

longitude                  3.7900
latitude                   3.7900
housing_median_age        19.0000
total_rooms             1693.0000
total_bedrooms           351.0000
population               935.0000
households               324.0000
median_income              2.1803
median_house_value    145200.0000
dtype: float64

In [16]:
# remove outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

numeric_cols = missing_dropped_df.select_dtypes(include='number').columns

missing_outliers_dropped_df = missing_dropped_df[
    ~((missing_dropped_df[numeric_cols] < lower_bound) |
     (missing_dropped_df[numeric_cols] > upper_bound)).any(axis=1)
]

missing_outliers_dropped_df.shape

(17434, 10)

In [17]:
outlier_rows_dropped = missing_dropped_df.shape[0] - missing_outliers_dropped_df.shape[0]
print('rows dropped:', outlier_rows_dropped)

print('before dropping outlier data rows:', missing_dropped_df.shape)
print('after dropping outlier data rows:', missing_outliers_dropped_df.shape)

# data removed percentage
percent_lost2 = round((100*outlier_rows_dropped)/float(missing_dropped_df.shape[0]))
percent_lost3 = round((100*(rows_dropped + outlier_rows_dropped))/float(housing_df.shape[0]))
print(f'{percent_lost2}% of rows removed from dataset without missing data rows')
print(f'original dataset: {housing_df.shape}')
print(f'{percent_lost3}% of rows removed from orignal dataset')

rows dropped: 2999
before dropping outlier data rows: (20433, 10)
after dropping outlier data rows: (17434, 10)
15% of rows removed from dataset without missing data rows
original dataset: (20640, 10)
16% of rows removed from orignal dataset

In [18]:
# before removing outliers
missing_dropped_df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20433.000000,20433.000000,20433.000000,20433.000000,20433.000000,20433.000000,20433.000000,20433.000000,20433.000000
mean,-119.570689,35.633221,28.633094,2636.504233,537.870553,1424.946949,499.433465,3.871162,206864.413155
std,2.003578,2.136348,12.591805,2185.269567,421.385070,1133.208490,382.299226,1.899291,115435.667099
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1450.000000,296.000000,787.000000,280.000000,2.563700,119500.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.536500,179700.000000
75%,-118.010000,37.720000,37.000000,3143.000000,647.000000,1722.000000,604.000000,4.744000,264700.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [19]:
# after removing outliers
missing_outliers_dropped_df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17434.000000,17434.000000,17434.000000,17434.000000,17434.000000,17434.000000,17434.000000,17434.000000,17434.000000
mean,-119.605773,35.697862,29.489216,2144.865206,445.472697,1197.108294,416.806126,3.575593,187056.188826
std,2.004422,2.166633,12.214437,1088.703854,221.276085,601.851013,205.412687,1.443540,93742.859159
min,-124.350000,32.540000,1.000000,2.000000,2.000000,3.000000,2.000000,0.499900,14999.000000
25%,-121.790000,33.940000,19.000000,1377.000000,287.000000,766.250000,271.000000,2.490150,112900.000000
50%,-118.610000,34.310000,30.000000,1979.000000,411.000000,1111.000000,387.000000,3.390600,170100.000000
75%,-118.030000,37.740000,38.000000,2782.000000,578.000000,1559.000000,540.000000,4.487950,241600.000000
max,-114.490000,41.950000,52.000000,5675.000000,1173.000000,3124.000000,1090.000000,8.011300,482200.000000

In [20]:
# change in mean before and after dropping outlier data rows
print("change in mean before and after dropping outlier data rows from dataset without missing data rows:")
((missing_outliers_dropped_df.mean(numeric_only=True) - missing_dropped_df.mean(numeric_only=True)) / missing_dropped_df.mean(numeric_only=True) * 100).round(2)

change in mean before and after dropping outlier data rows from dataset without missing data rows:

longitude              0.03
latitude               0.18
housing_median_age     2.99
total_rooms          -18.65
total_bedrooms       -17.18
population           -15.99
households           -16.54
median_income         -7.64
median_house_value    -9.58
dtype: float64

In [21]:
print("change in mean before and after dropping outlier data rows from original dataset:")
((missing_outliers_dropped_df.mean(numeric_only=True) - housing_df.mean(numeric_only=True)) / housing_df.mean(numeric_only=True) * 100).round(2)

change in mean before and after dropping outlier data rows from original dataset:

longitude              0.03
latitude               0.19
housing_median_age     2.97
total_rooms          -18.62
total_bedrooms       -17.18
population           -16.02
households           -16.56
median_income         -7.62
median_house_value    -9.57
dtype: float64

In [22]:
missing_outliers_dropped_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17434 entries, 2 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17434 non-null  float64
 1   latitude            17434 non-null  float64
 2   housing_median_age  17434 non-null  float64
 3   total_rooms         17434 non-null  float64
 4   total_bedrooms      17434 non-null  float64
 5   population          17434 non-null  float64
 6   households          17434 non-null  float64
 7   median_income       17434 non-null  float64
 8   median_house_value  17434 non-null  float64
 9   ocean_proximity     17434 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.5+ MB

In [23]:
housing_cleaned = missing_outliers_dropped_df

# Assignment 4 - Data Transformation

In [24]:
# Split the features and target (Model should use features to predict the target)
X = housing_cleaned.drop(["longitude", "total_bedrooms", "population", "median_house_value"], axis=1)
y = housing_cleaned["median_house_value"]

# Split column types into categorical and numerical
categorical_features = ["ocean_proximity"]

numerical_features = [
    "latitude",
    "housing_median_age",
    "total_rooms", "households"
     ,"median_income"
]

In [25]:
# Using sklearn to implement data transformation
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

# Using StandardScaler to scale all numerical columns to be comparable
# Using OneHotEncoder to convert text to numbers
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numerical_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)

# The transformed numeric dataset ready for ML
X_transformed = preprocessor.fit_transform(X)

In [27]:
# Splitting the data into 80% training and 20% testing
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_transformed,
    y,
    test_size=0.2,
    random_state=42
)

In [28]:
# Cleaned Data (Human View)
housing_cleaned.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
5,-122.25,37.85,52.0,919.0,213.0,413.0,193.0,4.0368,269700.0,NEAR BAY
6,-122.25,37.84,52.0,2535.0,489.0,1094.0,514.0,3.6591,299200.0,NEAR BAY

In [29]:
# Transformed Data (Machine View)
pd.DataFrame(X_transformed).head()

          0         1         2         3         4    5    6    7    8    9
0  0.993339  1.843018 -0.622653 -1.167469  2.550613  0.0  0.0  0.0  1.0  0.0
1  0.993339  1.843018 -0.799933 -0.962997  1.432289  0.0  0.0  0.0  1.0  0.0
2  0.993339  1.843018 -0.475685 -0.768261  0.187466  0.0  0.0  0.0  1.0  0.0
3  0.993339  1.843018 -1.126018 -1.089575  0.319507  0.0  0.0  0.0  1.0  0.0
4  0.988723  1.843018  0.358358  0.473177  0.057851  0.0  0.0  0.0  1.0  0.0

# Assignment 5 - Linear Regression

In [30]:
from sklearn import linear_model
model_reg = linear_model.LinearRegression()
model_reg.fit(X_train, y_train)

LinearRegression()

In [31]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import root_mean_squared_error

y_pred_linear = model_reg.predict(X_test)
print("R^2 Score (Testing Data): ", model_reg.score(X_test, y_test))
print("R^2 Score (Training Data): ", model_reg.score(X_train, y_train))
print("Mean Squared Error: ", mean_squared_error(y_test, y_pred_linear))
print("Mean Absolute Error: ", mean_absolute_error(y_test, y_pred_linear))
print("Root Mean Squared Error: ", root_mean_squared_error(y_test, y_pred_linear))

R^2 Score (Testing Data):  0.5628857546666706
R^2 Score (Training Data):  0.56438564299676
Mean Squared Error:  3807528100.472515
Mean Absolute Error:  46565.87197679689
Root Mean Squared Error:  61705.170775815175

# Assignment 5 - Random Forest

In [32]:
from sklearn.ensemble import RandomForestRegressor

forest_reg = RandomForestRegressor(random_state=42, n_estimators=500, max_depth=8, min_samples_leaf=10)
forest_reg.fit(X_train, y_train)

RandomForestRegressor(max_depth=8, min_samples_leaf=10, n_estimators=500,
                      random_state=42)

In [33]:
from sklearn.metrics import mean_squared_error
y_pred_forest = forest_reg.predict(X_test)
print("R^2 Score (Testing Data): ", forest_reg.score(X_test, y_test))
print("R^2 Score (Training Data): ", forest_reg.score(X_train, y_train))
print("Mean Squared Error: ", mean_squared_error(y_test, y_pred_forest))
print("Mean Absolute Error: ", mean_absolute_error(y_test, y_pred_forest))
print("Root Mean Squared Error: ", root_mean_squared_error(y_test, y_pred_forest))

R^2 Score (Testing Data):  0.649315897253079
R^2 Score (Training Data):  0.6880284638950712
Mean Squared Error:  3054669551.159745
Mean Absolute Error:  40331.99394048135
Root Mean Squared Error:  55269.06504691159

In [34]:
error_results = pd.DataFrame({
    "Actual Value": y_test,
    "Predicted Value": y_pred_forest
})

error_results["Error"] = error_results["Actual Value"] - error_results["Predicted Value"]
error_results["Absolute Error"] = abs(error_results["Error"])

worst_predictions = error_results.sort_values(
    by="Absolute Error",
    ascending=False
).head(10)

print(worst_predictions)

       Actual Value  Predicted Value          Error  Absolute Error
13360      416700.0    109591.062775  307108.937225   307108.937225
5464       425000.0    155636.896302  269363.103698   269363.103698
8944       461100.0    198707.436941  262392.563059   262392.563059
14448      450000.0    198579.229326  251420.770674   251420.770674
61          75000.0    316707.138215 -241707.138215   241707.138215
7262       350000.0    114420.588652  235579.411348   235579.411348
4717       450000.0    227406.415283  222593.584717   222593.584717
8303       461500.0    238947.155493  222552.844507   222552.844507
4696       453400.0    231734.385663  221665.614337   221665.614337
10953      350000.0    129513.428760  220486.571240   220486.571240